// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usar variáveis de ambiente com prefixo VITE_ para compatibilidade
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gyogfvfmsotveacjcckr.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5b2dmdmZtc290dmVhY2pjY2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTE1MjcsImV4cCI6MjA2MTI2NzUyN30.pVe1___osLxHnWo4dFzbNVRaQtAIOt997FSb2OlGK24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'control-auth-token',
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    autoRefreshToken: true,
  }
});